#%RAML 1.0 NamedExample

value: 
  - id: "1"
    fname: "Donald"
    lname: "Trump"
    department: "golf"
  - id: "2"
    fname: "kobe"
    lname: "Bryant"
    department: "nba"
  - id: "3"
    fname: "Barak"
    lname: "Obama"
    department: "rap"